# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LogLikeliHood_FULL <- function(param, datax, n_explanatory, n_transition, prob_initial_state_0, printLogLike) {
    .Call(`_TVTP_LogLikeliHood_FULL`, param, datax, n_explanatory, n_transition, prob_initial_state_0, printLogLike)
}

LogLikeliHood <- function(param, datax, n_explanatory, n_transition, prob_initial_state_0, printLogLike) {
    .Call(`_TVTP_LogLikeliHood`, param, datax, n_explanatory, n_transition, prob_initial_state_0, printLogLike)
}

LogLikeliHood_byObs <- function(param, datax, n_explanatory, n_transition, prob_initial_state_0, printLogLike) {
    .Call(`_TVTP_LogLikeliHood_byObs`, param, datax, n_explanatory, n_transition, prob_initial_state_0, printLogLike)
}

LogLikeliHood_min <- function(param, datax, n_explanatory, n_transition, prob_initial_state_0, printLogLike) {
    .Call(`_TVTP_LogLikeliHood_min`, param, datax, n_explanatory, n_transition, prob_initial_state_0, printLogLike)
}

LogLikeliHood_RunTimeCheck <- function(param, datax, n_explanatory, n_transition, prob_initial_state_0, printLogLike, n_it) {
    .Call(`_TVTP_LogLikeliHood_RunTimeCheck`, param, datax, n_explanatory, n_transition, prob_initial_state_0, printLogLike, n_it)
}

ReturnTiny <- function() {
    .Call(`_TVTP_ReturnTiny`)
}

